import mongoose from 'mongoose';

/**
 * Account Schema
 * Represents a ledger account (Asset, Liability, Equity, Revenue, or Expense)
 * 
 * Converted from SQLite table:
 * CREATE TABLE accounts (
 *   id TEXT PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   type TEXT NOT NULL,
 *   balance_cents INTEGER NOT NULL DEFAULT 0,
 *   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
 * )
 * 
 * Changes in MongoDB:
 * - SQLite TEXT id becomes Mongoose _id (auto-generated by MongoDB)
 * - balance_cents removed (calculated from transactions, not stored)
 * - created_at becomes createdAt with automatic timestamp
 */
const accountSchema = new mongoose.Schema(
  {
    // Account name (e.g., "Cash Account", "Customer A")
    name: {
      type: String,
      required: [true, 'Account name is required'],
      trim: true,
    },

    // Account type: ASSET, LIABILITY, EQUITY, REVENUE, or EXPENSE
    type: {
      type: String,
      enum: ['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'],
      required: [true, 'Account type is required'],
    },

    // Note: balance is NOT stored here because we calculate it from transactions
    // This ensures audit trail integrity - the transaction log is the source of truth
    // Balance calculation: SUM(credits) - SUM(debits) for this account
  },
  {
    // Automatically add createdAt and updatedAt timestamps
    timestamps: true,
  }
);

// Index for faster queries on account type (common filter)
accountSchema.index({ type: 1 });

// Create the Account model from the schema
// Mongoose automatically creates a collection named 'accounts' (lowercase, plural)
const Account = mongoose.model('Account', accountSchema);

export default Account;
